name: Alertas financieras

on:
  workflow_dispatch:

# Previene ejecuciones simultáneas que colisionen al modificar el JSON
concurrency:
  group: alertas-financieras-group
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  check-fondos:
    runs-on: ubuntu-latest
    timeout-minutes: 25 # Detiene el job completo si excede 25 minutos
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Descarga el historial completo para permitir `git pull --rebase` sin errores

      - name: Configurar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar dependencias
        run: |
          options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))
          install.packages(c("httr", "readxl", "digest", "jsonlite", "rvest", "stringr"))
        shell: Rscript {0}

      - name: Ejecutar Script de Fondos
        timeout-minutes: 25 # Garantiza que la ejecución del script no exceda los 25 minutos
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MULT_LIQ: ${{ vars.MULT_LIQ }}
          MULT_FLEX: ${{ vars.MULT_FLEX }}
          MULT_DOLAR: ${{ vars.MULT_DOLAR }}
        run: Rscript script.R

      - name: Guardar estado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add estado_hashes.json
          git diff --staged --quiet || git commit -m "Update fondos state"
          git pull --rebase origin main
          git push origin main
